version: "3"
networks:
    wp-networks:
        driver: bridge

services:
    mysql:
        image: mysql:latest
        container_name: wp-mysql-service
        tty: true
        ports:
            - "1033:3306"
        volumes:
            - "./bd:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pablo_fernandez
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: hola01
        networks:
            - wp-networks

    server:
        image: wordpress:latest
        container_name: wp-wordpress-service
        ports:
            - "8000:80"
        volumes:
            - "./wordpress:/var/www/html"
        environment:
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: hola01
            WORDPRESS_DB_NAME: pablo_fernandez
            WORDPRESS_DB_HOST: wp-mysql-service
        depends_on:
            - mysql
        networks:
            - wp-networks

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: wp-phpmyadmin-service
        ports:
            - "8080:80"
        environment:
            PMA_HOST: wp-mysql-service
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - mysql
        networks:
            - wp-networks

